In [1]:
import numpy as np
import matplotlib.pyplot

In [2]:
#输入数据
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
#标签
Y = np.array([[0],
              [1],
              [1],
              [0]])
#生成3行一列（-1,1）之间的数据  因为三个输入一个输出所以要三行一列
#np.random.random() 生成的是0-1之间的数据
V = (np.random.random([3,4])-0.5)*2
W = (np.random.random([4,1])-0.5)*2
print(V)

lr = 0.11

def sigmoid(x):
    return 1/(1+np.exp(-x))

def dsigmoid(x):
    return x*(1-x)

def update():
    global X,Y,W,V,lr
    L1 = sigmoid(np.dot(X,V)) #隐藏层输出 4*4 h 1
    L2 = sigmoid(np.dot(L1,W)) #输出层 4*1 h 1
    L2_delta = (Y - L2)*dsigmoid(L2) #4*1 h 1 
    L1_delta = L2_delta.dot(W.T) * dsigmoid(L1) # 4*4 h 1    
    W_C = lr*L1.T.dot(L2_delta)
    V_C = lr*X.T.dot(L1_delta)
    W = W + W_C
    V = V + V_C

[[ 0.20558613 -0.81601189 -0.91813463 -0.99677813]
 [ 0.66141602  0.63601042  0.14497139  0.95750326]
 [-0.45551845 -0.5853089   0.12334691 -0.41822556]]


In [4]:
for i in range(20000):
    update()
    if i%500 ==0: 
        L1 = sigmoid(np.dot(X,V)) #隐藏层输出 4*4 h 1
        L2 = sigmoid(np.dot(L1,W)) #输出层 4*1 h 1 
        print("Error:",np.mean(np.abs(Y-L2)))

Error: 0.02403470569018855
Error: 0.023625947624171077
Error: 0.023235557786598433
Error: 0.022862262521100737
Error: 0.022504905025298894
Error: 0.022162432174018618
Error: 0.021833883091438504
Error: 0.02151837920656887
Error: 0.021215115571698674
Error: 0.020923353260166887
Error: 0.020642412689785408
Error: 0.020371667742788157
Error: 0.02011054057340561
Error: 0.019858497010881954
Error: 0.019615042479629207
Error: 0.019379718369783694
Error: 0.019152098801104432
Error: 0.018931787731280864
Error: 0.018718416366558712
Error: 0.018511640838378807
Error: 0.018311140114627172
Error: 0.01811661411826473
Error: 0.017927782029665138
Error: 0.017744380752025647
Error: 0.01756616352183188
Error: 0.017392898648594685
Error: 0.017224368370014627
Error: 0.017060367810400066
Error: 0.01690070403161095
Error: 0.016745195167057025
Error: 0.016593669630374692
Error: 0.016445965391356794
Error: 0.0163019293125438
Error: 0.01616141654061453
Error: 0.016024289947352804
Error: 0.015890419615528895
E